'use client';

import { useEffect, useState } from 'react';
import updates from '@/data/updates.json';

interface Update {
  id: string;
  date: string;
  title: string;
  description: string;
  source: string;
  url?: string;
  category: "model" | "lab" | "research" | "product" | "market" | "policy";
}

const categoryLabels: Record<string, string> = {
  model: 'MODEL',
  lab: 'LAB',
  research: 'RESEARCH',
  product: 'PRODUCT',
  market: 'MARKET',
  policy: 'POLICY',
};

export default function PrintTimeline() {
  const [mounted, setMounted] = useState(false);
  
  useEffect(() => {
    setMounted(true);
    const timer = setTimeout(() => window.print(), 500);
    return () => clearTimeout(timer);
  }, []);

  const grouped = (updates as Update[]).reduce((acc, item) => {
    const date = new Date(item.date);
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
    if (!acc[key]) acc[key] = [];
    acc[key].push(item);
    return acc;
  }, {} as Record<string, Update[]>);

  const sortedMonths = Object.keys(grouped).sort().reverse();

  if (!mounted) return null;

  return (
    <div className="print-container">
      <style>{`
        @media print {
          @page { size: A4; margin: 15mm; }
          body { background: white !important; color: black !important; }
          .no-print { display: none !important; }
        }
        @media screen {
          .print-container {
            max-width: 210mm;
            margin: 0 auto;
            padding: 20mm;
            background: white;
            color: black;
            min-height: 100vh;
          }
        }
      `}</style>
      
      <div className="no-print fixed top-4 right-4 flex gap-2 z-50">
        <button onClick={() => window.print()} className="bg-black text-white px-4 py-2 font-mono text-sm">
          PRINT / SAVE PDF
        </button>
        <button onClick={() => window.close()} className="border border-black px-4 py-2 font-mono text-sm">
          CLOSE
        </button>
      </div>

      <header className="border-b-2 border-black pb-6 mb-8">
        <h1 className="text-4xl font-bold tracking-tight mb-2">AI TIMELINE</h1>
        <p className="text-sm text-gray-600 font-mono">
          Printed {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </header>

      <div className="space-y-8">
        {sortedMonths.map(monthKey => {
          const [year, month] = monthKey.split('-');
          const monthName = new Date(parseInt(year), parseInt(month) - 1).toLocaleDateString('en-US', {
            month: 'long', year: 'numeric'
          });
          
          return (
            <section key={monthKey} className="break-inside-avoid">
              <h2 className="text-xl font-bold border-b border-gray-300 pb-2 mb-4 uppercase">
                {monthName}
              </h2>
              <div className="space-y-4">
                {grouped[monthKey]
                  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                  .map(item => (
                    <div key={item.id} className="border-l-2 border-gray-200 pl-4 py-1">
                      <div className="flex items-baseline gap-3 mb-1">
                        <span className="text-xs font-mono text-gray-500">
                          {new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                        </span>
                        <span className="text-xs font-mono text-gray-400">{categoryLabels[item.category]}</span>
                      </div>
                      <h3 className="font-semibold text-base mb-1">{item.title}</h3>
                      <p className="text-sm text-gray-700">{item.description}</p>
                    </div>
                  ))}
              </div>
            </section>
          );
        })}
      </div>

      <footer className="mt-12 pt-6 border-t border-gray-200 text-center">
        <p className="text-xs text-gray-400 font-mono">Generated by AI Timeline • {updates.length} entries</p>
      </footer>
    </div>
  );
}
